Fix 3.9 build
After manually debugging requests_kerberos I discovered the missing .so file.

ImportError: Error loading shared library libgssapi_krb5.so.2: \
  No such file or directory (needed by /usr/lib/python2.7/site-packages/kerberos.so)